//! Aggregate trait extensions and generator macros.
//!
//! [`Aggregate`] is a convenience supertrait over
//! [`ddd_shared_kernel::AggregateRoot`] that adds the `Send + Sync` bounds needed
//! for async repositories.

use ddd_shared_kernel::AggregateRoot;

/// Marker supertrait for async-ready aggregate roots.
pub trait Aggregate: AggregateRoot + Send + Sync {}

impl<T> Aggregate for T where T: AggregateRoot + Send + Sync {}

/// Generate an aggregate struct with the standard DDD fields plus custom ones.
///
/// The generated struct has:
/// - `id: $id_type`
/// - `version: u64`
/// - `created_at: chrono::DateTime<chrono::Utc>`
/// - `updated_at: chrono::DateTime<chrono::Utc>`
/// - `domain_events: Vec<Box<dyn ddd_shared_kernel::DomainEvent>>`
/// - any fields you pass in the `{ ... }` block
///
/// # Example
/// ```ignore
/// use ddd_domain::define_aggregate;
/// use ddd_shared_kernel::declare_id;
///
/// declare_id!(ProductId);
///
/// define_aggregate!(Product, ProductId, {
///     pub name: String,
///     pub price: u64,
/// });
/// ```
#[macro_export]
macro_rules! define_aggregate {
    ($name:ident, $id_type:ty, { $($(#[$fmeta:meta])* $fvis:vis $fname:ident : $ftype:ty),* $(,)? }) => {
        /// Aggregate root generated by `define_aggregate!`.
        #[derive(Debug)]
        pub struct $name {
            /// Aggregate identity.
            pub id: $id_type,
            /// Optimistic-concurrency version.
            pub version: u64,
            /// Creation timestamp.
            pub created_at: ::chrono::DateTime<::chrono::Utc>,
            /// Last-modified timestamp.
            pub updated_at: ::chrono::DateTime<::chrono::Utc>,
            /// Pending uncommitted domain events.
            pub domain_events: ::std::vec::Vec<::std::boxed::Box<dyn ::ddd_shared_kernel::DomainEvent>>,
            $(
                $(#[$fmeta])*
                $fvis $fname: $ftype,
            )*
        }
    };
}

/// Implement [`ddd_shared_kernel::AggregateRoot`] for a struct produced by
/// [`define_aggregate!`] (or any struct with the same field layout).
///
/// This is a thin forwarder to [`ddd_shared_kernel::impl_aggregate_root!`].
#[macro_export]
macro_rules! impl_aggregate {
    ($name:ty, $id_type:ty) => {
        ::ddd_shared_kernel::impl_aggregate_root!($name, $id_type);
    };
}

/// Add ergonomic event-recording methods to an aggregate.
///
/// Generates `record_event` and `clear_events` inherent methods on `$name`.
#[macro_export]
macro_rules! impl_aggregate_events {
    ($name:ty) => {
        impl $name {
            /// Record a domain event on the aggregate's pending buffer.
            pub fn record_event<E>(&mut self, event: E)
            where
                E: ::ddd_shared_kernel::DomainEvent + 'static,
            {
                self.domain_events.push(::std::boxed::Box::new(event));
            }

            /// Clear all pending domain events without dispatching them.
            pub fn clear_events(&mut self) {
                self.domain_events.clear();
            }
        }
    };
}
