//! Domain service traits and generator macro.

use std::marker::PhantomData;

use crate::aggregate::Aggregate;

/// Marker trait for any stateless domain service.
pub trait DomainService: Send + Sync {}

/// Marker trait for domain services that operate on a specific aggregate.
pub trait DomainServiceFor<A: Aggregate>: DomainService {}

/// Generate a domain service struct tied (optionally) to an aggregate.
///
/// Produces a unit-like struct implementing [`DomainService`], a `new()`
/// constructor, and the listed method signatures as inherent methods. The
/// bodies default to `unimplemented!()` — override by writing your own
/// `impl $ServiceName { ... }` block after the macro invocation.
///
/// # Examples
/// ```ignore
/// use ddd_domain::define_domain_service;
/// # struct Product;
/// # struct Money;
///
/// define_domain_service!(PricingService, Product, {
///     fn calculate_discount(&self, product: &Product) -> Money;
/// });
/// ```
#[macro_export]
macro_rules! define_domain_service {
    ($name:ident) => {
        $crate::define_domain_service!(@core $name);
    };
    ($name:ident, { $($methods:tt)* }) => {
        $crate::define_domain_service!(@core $name);
        impl $name {
            $($methods)*
        }
    };
    ($name:ident, $aggregate:ty) => {
        $crate::define_domain_service!(@core $name);
        impl $crate::domain_service::DomainServiceFor<$aggregate> for $name {}
    };
    ($name:ident, $aggregate:ty, { $($methods:tt)* }) => {
        $crate::define_domain_service!(@core $name);
        impl $crate::domain_service::DomainServiceFor<$aggregate> for $name {}
        impl $name {
            $($methods)*
        }
    };
    (@core $name:ident) => {
        /// Domain service generated by `define_domain_service!`.
        #[derive(Debug, Default, Clone, Copy)]
        pub struct $name;

        impl $name {
            /// Construct a new instance of the service.
            #[must_use]
            pub fn new() -> Self {
                Self
            }
        }

        impl $crate::domain_service::DomainService for $name {}
    };
}

/// Generic typed wrapper for a domain service bound to a specific aggregate.
///
/// Rarely needed directly — prefer [`define_domain_service!`].
#[derive(Debug, Default, Clone, Copy)]
pub struct TypedDomainService<A: Aggregate>(PhantomData<A>);

impl<A: Aggregate> TypedDomainService<A> {
    /// Create a new typed service marker.
    #[must_use]
    pub fn new() -> Self {
        Self(PhantomData)
    }
}

impl<A: Aggregate> DomainService for TypedDomainService<A> {}
impl<A: Aggregate> DomainServiceFor<A> for TypedDomainService<A> {}
