//! Non-aggregate entity helpers.
//!
//! Entities share a single [`Entity`] trait with the shared kernel — this
//! module only re-exports that trait and layers on the [`define_entity!`]
//! generator macro for non-aggregate entities.

pub use ddd_shared_kernel::Entity;

/// Generate an entity struct with an `id` field plus custom fields.
///
/// The generated struct implements [`ddd_shared_kernel::Entity`]. Unlike
/// [`crate::define_aggregate!`], entities have no version counter or
/// domain-event buffer.
///
/// # Example
/// ```ignore
/// use ddd_domain::define_entity;
/// use ddd_shared_kernel::declare_id;
///
/// declare_id!(LineItemId);
///
/// define_entity!(LineItem, LineItemId, {
///     pub sku: String,
///     pub quantity: u32,
/// });
/// ```
#[macro_export]
macro_rules! define_entity {
    ($name:ident, $id_type:ty, { $($(#[$fmeta:meta])* $fvis:vis $fname:ident : $ftype:ty),* $(,)? }) => {
        /// Entity generated by `define_entity!`.
        #[derive(Debug, Clone)]
        pub struct $name {
            /// Entity identity.
            pub id: $id_type,
            $(
                $(#[$fmeta])*
                $fvis $fname: $ftype,
            )*
        }

        impl ::ddd_shared_kernel::Entity for $name {
            type Id = $id_type;
            fn id(&self) -> &Self::Id {
                &self.id
            }
        }
    };
}
