//! Generic repository trait and macro for bounded-context repositories.

use async_trait::async_trait;
use ddd_shared_kernel::{AggregateRoot, AppResult};

use crate::aggregate::Aggregate;

/// Generic CRUD repository for an aggregate root.
///
/// Bounded contexts should typically *extend* this trait (see
/// [`define_repository!`]) rather than using it directly, so they can add
/// query methods specific to their aggregate.
#[async_trait]
pub trait Repository<A: Aggregate>: Send + Sync {
    /// Load an aggregate by its identity.
    async fn find_by_id(&self, id: <A as AggregateRoot>::Id) -> AppResult<Option<A>>;

    /// Insert a new aggregate.
    async fn save(&self, aggregate: &A) -> AppResult<()>;

    /// Persist changes to an existing aggregate.
    async fn update(&self, aggregate: &A) -> AppResult<()>;

    /// Delete an aggregate by its identity.
    async fn delete(&self, id: <A as AggregateRoot>::Id) -> AppResult<()>;

    /// Check whether an aggregate with the given id exists.
    async fn exists(&self, id: <A as AggregateRoot>::Id) -> AppResult<bool>;
}

/// Generate a bounded-context repository trait that extends [`Repository`].
///
/// # Example
/// ```ignore
/// use ddd_domain::define_repository;
/// # struct Product; // assume Aggregate impl exists
///
/// define_repository!(ProductRepository, Product, {
///     async fn find_by_name(&self, name: &str)
///         -> ddd_shared_kernel::AppResult<Vec<Product>>;
/// });
/// ```
#[macro_export]
macro_rules! define_repository {
    ($repo_name:ident, $aggregate:ty) => {
        /// Repository trait generated by `define_repository!`.
        #[::async_trait::async_trait]
        pub trait $repo_name:
            $crate::repository::Repository<$aggregate> + ::std::marker::Send + ::std::marker::Sync
        {
        }
    };
    ($repo_name:ident, $aggregate:ty, { $($methods:tt)* }) => {
        /// Repository trait generated by `define_repository!`.
        #[::async_trait::async_trait]
        pub trait $repo_name:
            $crate::repository::Repository<$aggregate> + ::std::marker::Send + ::std::marker::Sync
        {
            $($methods)*
        }
    };
}
