use ddd_api::prelude::*;
use ddd_api::{GrpcServer, error_mapping_interceptor};
use tonic::{transport::Server, Request, Response, Status};

// 1. Hypothetical Proto-generated service trait
// In a real app, this is generated by tonic-build
#[tonic::async_trait]
pub trait Greeter: Send + Sync + 'static {
    async fn say_hello(&self, request: Request<HelloRequest>) -> Result<Response<HelloReply>, Status>;
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct HelloRequest { pub name: String }
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct HelloReply { pub message: String }

// 2. Implementation with error mapping
struct MyGreeter;

#[tonic::async_trait]
impl Greeter for MyGreeter {
    async fn say_hello(&self, request: Request<HelloRequest>) -> Result<Response<HelloReply>, Status> {
        let name = request.into_inner().name;
        
        if name == "error" {
            // Convert AppError to Tonic Status using the provided extensions
            return Err(AppError::validation("name", "Invalid name").into_grpc_status());
        }

        Ok(Response::new(HelloReply {
            message: format!("Hello {}!", name),
        }))
    }
}

// 3. Boilerplate to make it "runnable" without proto files
// In a real app, you'd use GreeterServer::new(MyGreeter)
struct MockGreeterServer;
impl tonic::transport::NamedService for MockGreeterServer {
    const NAME: &'static str = "greeter.Greeter";
}
impl tonic::server::Routes for MockGreeterServer {
    fn routes(&self) -> tonic::server::Router { tonic::server::Router::new() }
}

#[tokio::main]
async fn main() -> AppResult<()> {
    // 4. Build the Tonic Router with Interceptors
    let router = Server::builder()
        .layer(tonic::middleware::interceptor(error_mapping_interceptor))
        .add_service(MockGreeterServer);

    // 5. Run via GrpcServer wrapper for graceful shutdown
    println!("Starting gRPC server on :50051...");
    GrpcServer::new()
        .with_port(50051)
        .with_router(router)
        .run()
        .await?;

    Ok(())
}
