//! Demonstrates wiring up a gRPC server using `ddd-api`'s `GrpcServer` and
//! the `error_mapping_interceptor`.
//!
//! In a real project the service trait and server struct are generated by
//! `tonic-build` from a `.proto` file.  This example hand-rolls a minimal
//! service to illustrate the error-conversion and interceptor patterns without
//! requiring a proto compilation step.

use ddd_api::prelude::*;
use ddd_api::{GrpcServer, GrpcErrorExt};
use tonic::{Request, Response, Status};

// ─── Hand-rolled service (replace with tonic-generated code in production) ───

pub struct HelloRequest {
    pub name: String,
}

pub struct HelloReply {
    pub message: String,
}

pub struct MyGreeter;

impl MyGreeter {
    /// Equivalent to the generated handler body: converts `AppError` →
    /// `tonic::Status` via [`GrpcErrorExt::to_grpc_status`].
    async fn say_hello(
        &self,
        request: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        let name = request.into_inner().name;

        if name.is_empty() {
            // Convert AppError → Status with RFC 9457 metadata attached.
            return Err(AppError::validation("name", "Name must not be empty")
                .to_grpc_status());
        }

        Ok(Response::new(HelloReply {
            message: format!("Hello, {name}!"),
        }))
    }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> AppResult<()> {
    // Demonstrate error conversion.
    let greeter = MyGreeter;
    let req = Request::new(HelloRequest { name: "World".into() });
    let reply = greeter.say_hello(req).await.unwrap();
    println!("Reply: {}", reply.into_inner().message);

    // In a real project, wire `error_mapping_interceptor` at the service level:
    //
    //   let svc = GreeterServer::with_interceptor(MyGreeter, error_mapping_interceptor);
    //   let router = tonic::transport::Server::builder().add_service(svc);
    //   GrpcServer::new().with_port(50051).with_router(router).run().await?;
    //
    // `GrpcServer` adds graceful shutdown (SIGTERM / SIGINT) on top of the raw
    // tonic router so the server drains in-flight RPCs before exiting.

    println!("GrpcServer is ready to be configured with a proto-generated router.");
    let _server = GrpcServer::new().with_port(50051);

    Ok(())
}
