//! Axum observability middleware — request logging + Prometheus metrics.
//!
//! Provides an axum [`axum::middleware::from_fn_with_state`]-compatible
//! middleware that:
//! - Generates or forwards `x-request-id` (UUID v7) for correlation.
//! - Captures client IP from `X-Forwarded-For` or `ConnectInfo`.
//! - Extracts W3C `traceparent`/`tracestate` headers and stores them as
//!   request extensions for downstream propagation.
//! - Optionally logs request/response bodies at `DEBUG` level with
//!   sensitive-field redaction.
//! - Logs one structured line per request (method, path, status, latency,
//!   request_id, client_ip).
//! - Tracks `bff_http_requests_total`, `bff_http_request_duration_seconds`,
//!   and `bff_http_requests_in_flight` via [`crate::metrics::BFF_METRICS`].
//!
//! Feature-gated on `axum-response`.

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Instant;

use axum::body::Body;
use axum::extract::{ConnectInfo, State};
use axum::http::{Extensions, HeaderMap, HeaderValue, Request};
use axum::middleware::Next;
use axum::response::{IntoResponse, Response};
use http_body_util::BodyExt;
use uuid::Uuid;

use crate::metrics::BFF_METRICS;
use super::redaction::redact_json_string;

// ─── Public types ────────────────────────────────────────────────────────────

/// State injected into the observability middleware.
///
/// Pass `redact_fields` to scrub sensitive fields before logging request
/// bodies.  Set `log_bodies` to `true` to enable request/response body
/// logging (behind `DEBUG` log level).
#[derive(Clone)]
pub struct ObservabilityState {
    pub redact_fields: Arc<Vec<String>>,
    /// When `true` **and** the `DEBUG` log level is enabled, request and
    /// response JSON bodies are logged (redacted).  Defaults to `false`.
    pub log_bodies: bool,
}

/// W3C trace-context headers extracted from the inbound request.
///
/// Stored as a request extension so handlers (and tonic interceptors) can
/// forward them to downstream gRPC services without re-parsing headers.
#[derive(Debug, Clone, Default)]
pub struct RequestTraceContext {
    /// `x-request-id` — generated by the middleware if absent.
    pub request_id: String,
    /// W3C `traceparent` header value (if present).
    pub traceparent: Option<String>,
    /// W3C `tracestate` header value (if present).
    pub tracestate: Option<String>,
}

/// Client IP extracted from `X-Forwarded-For` (first entry) or the TCP
/// peer address.  Stored as a request extension.
#[derive(Debug, Clone)]
pub struct ClientIp(pub String);

// ─── Header names ────────────────────────────────────────────────────────────

const REQUEST_ID_HEADER: &str = "x-request-id";
const FORWARDED_FOR_HEADER: &str = "x-forwarded-for";

// ─── Middleware ──────────────────────────────────────────────────────────────

/// Axum middleware that logs every request and tracks Prometheus metrics.
///
/// Wire it with [`axum::middleware::from_fn_with_state`]:
///
/// ```ignore
/// use std::sync::Arc;
/// use axum::{middleware as axum_mw, Router};
/// use ddd_bff::middleware::axum_observability::{ObservabilityState, observability_middleware};
///
/// let obs_state = ObservabilityState {
///     redact_fields: Arc::new(vec!["password".into(), "token".into()]),
///     log_bodies: false,
/// };
/// let app = Router::new()
///     // ... routes ...
///     .layer(axum_mw::from_fn_with_state(obs_state, observability_middleware));
/// ```
pub async fn observability_middleware(
    State(obs): State<ObservabilityState>,
    req: Request<Body>,
    next: Next,
) -> impl IntoResponse {
    let start = Instant::now();
    let method = req.method().to_string();
    let path = req.uri().path().to_string();

    // ── Request ID ───────────────────────────────────────────────────────
    let request_id = extract_header(req.headers(), REQUEST_ID_HEADER)
        .unwrap_or_else(|| Uuid::now_v7().to_string());

    // ── Trace context ────────────────────────────────────────────────────
    let trace_ctx = RequestTraceContext {
        request_id: request_id.clone(),
        traceparent: extract_header(req.headers(), "traceparent"),
        tracestate: extract_header(req.headers(), "tracestate"),
    };

    // ── Client IP ────────────────────────────────────────────────────────
    let client_ip = extract_client_ip(req.headers(), req.extensions());

    // ── Metrics ──────────────────────────────────────────────────────────
    BFF_METRICS.in_flight.inc();

    tracing::info!(
        request_id = %request_id,
        method = %method,
        path = %path,
        client_ip = %client_ip,
        "incoming request"
    );

    // ── Body logging (request) ───────────────────────────────────────────
    let (parts, body) = req.into_parts();
    let body = if obs.log_bodies && tracing::enabled!(tracing::Level::DEBUG) {
        let bytes = body
            .collect()
            .await
            .map(|c| c.to_bytes())
            .unwrap_or_default();
        if !bytes.is_empty() {
            if let Ok(text) = std::str::from_utf8(&bytes) {
                let redacted = redact_json_string(text, &obs.redact_fields);
                tracing::debug!(
                    request_id = %request_id,
                    body = %redacted,
                    "request body"
                );
            }
        }
        Body::from(bytes)
    } else {
        body
    };

    // ── Re-assemble request with extensions ──────────────────────────────
    let mut req = Request::from_parts(parts, body);
    req.extensions_mut().insert(trace_ctx.clone());
    req.extensions_mut().insert(ClientIp(client_ip.clone()));

    // ── Dispatch ─────────────────────────────────────────────────────────
    let mut response = next.run(req).await;

    // ── Body logging (response) ──────────────────────────────────────────
    if obs.log_bodies && tracing::enabled!(tracing::Level::DEBUG) {
        let (resp_parts, resp_body) = response.into_parts();
        let bytes = resp_body
            .collect()
            .await
            .map(|c| c.to_bytes())
            .unwrap_or_default();
        if !bytes.is_empty() {
            if let Ok(text) = std::str::from_utf8(&bytes) {
                let redacted = redact_json_string(text, &obs.redact_fields);
                tracing::debug!(
                    request_id = %request_id,
                    body = %redacted,
                    "response body"
                );
            }
        }
        response = Response::from_parts(resp_parts, Body::from(bytes));
    }

    // ── Stamp response ──────────────────────────────────────────────────
    if let Ok(v) = HeaderValue::from_str(&request_id) {
        response.headers_mut().insert(REQUEST_ID_HEADER, v);
    }

    // ── Metrics + access log ─────────────────────────────────────────────
    let elapsed = start.elapsed().as_secs_f64();
    let status = response.status().as_u16().to_string();

    BFF_METRICS.in_flight.dec();
    BFF_METRICS
        .request_count
        .with_label_values(&[&path, &method, &status])
        .inc();
    BFF_METRICS
        .request_duration
        .with_label_values(&[&path, &method])
        .observe(elapsed);

    tracing::info!(
        request_id = %request_id,
        method = %method,
        path = %path,
        status = %status,
        client_ip = %client_ip,
        latency_ms = elapsed * 1000.0,
        "request completed"
    );

    response
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

fn extract_header(headers: &HeaderMap, name: &str) -> Option<String> {
    headers
        .get(name)
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_owned())
}

fn extract_client_ip(
    headers: &HeaderMap,
    extensions: &Extensions,
) -> String {
    // Prefer X-Forwarded-For (first entry) when behind a reverse proxy.
    if let Some(forwarded) = extract_header(headers, FORWARDED_FOR_HEADER) {
        if let Some(first) = forwarded.split(',').next() {
            let trimmed = first.trim();
            if !trimmed.is_empty() {
                return trimmed.to_owned();
            }
        }
    }
    // Fall back to the TCP peer address.
    if let Some(connect_info) = extensions.get::<ConnectInfo<SocketAddr>>() {
        return connect_info.0.ip().to_string();
    }
    "unknown".to_owned()
}
