use ddd_bff::openapi::{ApiRoute, RouteKind, Param, ResponseSpec, SchemaRef, inject_routes};
use serde_json::json;

// 1. Define the Route Table
// This table acts as the source of truth for both the gateway's router
// and its OpenAPI documentation.
const API_ROUTES: &[ApiRoute] = &[
    // A standard pass-through to a gRPC service
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order-service",
            grpc_method: "orders.v1.OrderService/GetOrder",
        },
        method: "GET",
        path: "/admin/orders/{id}",
        operation_id: "get_order",
        summary: "Get order by ID",
        tag: "Orders",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Unique order UUID",
        }],
        request_body: None,
        responses: &[
            ResponseSpec {
                status: 200,
                description: "Success",
                schema: Some(SchemaRef {
                    name: "OrderDto",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 404,
                description: "Order not found",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    // An aggregation endpoint (hand-written handler in the BFF)
    ApiRoute {
        kind: RouteKind::Aggregation,
        method: "GET",
        path: "/admin/dashboard/summary",
        operation_id: "get_summary",
        summary: "Aggregated dashboard data",
        tag: "Dashboard",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Combined results",
            schema: Some(SchemaRef {
                name: "DashboardSummary",
                content_type: "application/json",
            }),
        }],
    },
];

fn main() {
    // 2. Start with a base OpenAPI spec (typically generated by utoipa)
    let mut spec = json!({
        "openapi": "3.1.0",
        "info": { "title": "Admin BFF", "version": "1.0.0" },
        "paths": {},
        "components": {
            "schemas": {
                "ProblemDetail": { "type": "object", "properties": { "title": { "type": "string" } } }
                // Other schemas would be here...
            }
        }
    });

    // 3. Inject the declarative routes
    println!("Injecting {} routes into spec...", API_ROUTES.len());
    inject_routes(&mut spec, API_ROUTES);

    // 4. Output the result
    println!("\nGenerated OpenAPI Paths:");
    if let Some(paths) = spec["paths"].as_object() {
        for path in paths.keys() {
            println!("  - {}", path);
        }
    }

    // You can now serve this JSON via an Axum route or write it to a file.
    // println!("{}", serde_json::to_string_pretty(&spec).unwrap());
}
