use ddd_bff::openapi::{ApiRoute, Param, ResponseSpec, RouteKind, SchemaRef};

/// Declarative table of every BFF endpoint that should appear in the
/// merged OpenAPI document with `x-bff-kind` metadata. Adding a new
/// pass-through, aggregation, or streaming endpoint is a one-line
/// addition here — no per-handler `#[utoipa::path]` boilerplate and no
/// hand-rolled JSON injection required.
///
/// Schemas referenced below must already exist in `components.schemas`,
/// either because they derive `utoipa::ToSchema` (and are registered on
/// `AdminApiDoc` or via proto build-time derives) or because
/// `merged_openapi` folded them in from a downstream service spec.
pub const API_ROUTES: &[ApiRoute] = &[
    // ── Pass-through (REST → gRPC) ─────────────────────────────────────
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/CreateProduct",
        },
        method: "POST",
        path: "/admin/products",
        operation_id: "create_product",
        summary: "Create a product",
        tag: "Products",
        params: &[],
        request_body: Some(SchemaRef {
            name: "CreateProductRequest",
            content_type: "application/json",
        }),
        responses: &[
            ResponseSpec {
                status: 201,
                description: "Created",
                schema: Some(SchemaRef {
                    name: "CreateProductResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 400,
                description: "Validation error",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/GetProduct",
        },
        method: "GET",
        path: "/admin/products/{id}",
        operation_id: "get_product",
        summary: "Fetch a product by id",
        tag: "Products",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Product id (UUID)",
        }],
        request_body: None,
        responses: &[
            ResponseSpec {
                status: 200,
                description: "Found",
                schema: Some(SchemaRef {
                    name: "GetProductResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 404,
                description: "Not found",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/ListProducts",
        },
        method: "GET",
        path: "/admin/products",
        operation_id: "list_products",
        summary: "List products with pagination",
        tag: "Products",
        params: &[
            Param {
                name: "page",
                location: "query",
                required: false,
                schema_type: "integer",
                description: "Page number (default: 1)",
            },
            Param {
                name: "per_page",
                location: "query",
                required: false,
                schema_type: "integer",
                description: "Items per page (default: 20)",
            },
        ],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Page of products",
            schema: Some(SchemaRef {
                name: "ListProductsResponse",
                content_type: "application/json",
            }),
        }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/UpdateStock",
        },
        method: "PUT",
        path: "/admin/products/{id}/stock",
        operation_id: "update_stock",
        summary: "Update a product's stock level",
        tag: "Products",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Product id (UUID)",
        }],
        request_body: Some(SchemaRef {
            name: "UpdateStockRequest",
            content_type: "application/json",
        }),
        responses: &[ResponseSpec {
            status: 200,
            description: "Updated",
            schema: None,
        }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/DeactivateProduct",
        },
        method: "PUT",
        path: "/admin/products/{id}/deactivate",
        operation_id: "deactivate_product",
        summary: "Deactivate a product",
        tag: "Products",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Product id (UUID)",
        }],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Deactivated",
            schema: None,
        }],
    },
    // ── Aggregation (multi-call fan-out) ───────────────────────────────
    ApiRoute {
        kind: RouteKind::Aggregation,
        method: "GET",
        path: "/admin/catalog/summary",
        operation_id: "get_catalog_summary",
        summary: "Aggregate product counts and recent items",
        tag: "Aggregation",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Aggregated catalog summary",
            schema: None,
        }],
    },
    ApiRoute {
        kind: RouteKind::Aggregation,
        method: "POST",
        path: "/admin/orders/batch",
        operation_id: "batch_get_orders",
        summary: "Fetch many orders in parallel (partial-failure tolerant)",
        tag: "Aggregation",
        params: &[],
        request_body: Some(SchemaRef {
            name: "BatchRequest",
            content_type: "application/json",
        }),
        responses: &[
            ResponseSpec {
                status: 200,
                description: "Per-id results",
                schema: Some(SchemaRef {
                    name: "BatchResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 400,
                description: "Too many ids",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    // ── Orders (REST → gRPC pass-through) ─────────────────────────────
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order",
            grpc_method: "order.v1.OrderService/CreateOrder",
        },
        method: "POST",
        path: "/admin/orders",
        operation_id: "create_order",
        summary: "Place a new order",
        tag: "Orders",
        params: &[],
        request_body: Some(SchemaRef {
            name: "CreateOrderRequest",
            content_type: "application/json",
        }),
        responses: &[
            ResponseSpec {
                status: 201,
                description: "Created",
                schema: Some(SchemaRef {
                    name: "CreateOrderResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 400,
                description: "Validation error",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order",
            grpc_method: "order.v1.OrderService/GetOrder",
        },
        method: "GET",
        path: "/admin/orders/{id}",
        operation_id: "get_order",
        summary: "Fetch an order by id",
        tag: "Orders",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Order id (UUID)",
        }],
        request_body: None,
        responses: &[
            ResponseSpec {
                status: 200,
                description: "Found",
                schema: Some(SchemaRef {
                    name: "GetOrderResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 404,
                description: "Not found",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order",
            grpc_method: "order.v1.OrderService/ListOrders",
        },
        method: "GET",
        path: "/admin/orders",
        operation_id: "list_orders",
        summary: "List orders with pagination",
        tag: "Orders",
        params: &[
            Param {
                name: "page",
                location: "query",
                required: false,
                schema_type: "integer",
                description: "Page number (default: 1)",
            },
            Param {
                name: "per_page",
                location: "query",
                required: false,
                schema_type: "integer",
                description: "Items per page (default: 20)",
            },
        ],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Page of orders",
            schema: Some(SchemaRef {
                name: "ListOrdersResponse",
                content_type: "application/json",
            }),
        }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order",
            grpc_method: "order.v1.OrderService/ConfirmOrder",
        },
        method: "PUT",
        path: "/admin/orders/{id}/confirm",
        operation_id: "confirm_order",
        summary: "Confirm a pending order",
        tag: "Orders",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Order id (UUID)",
        }],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Confirmed",
            schema: None,
        }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "order",
            grpc_method: "order.v1.OrderService/CancelOrder",
        },
        method: "PUT",
        path: "/admin/orders/{id}/cancel",
        operation_id: "cancel_order",
        summary: "Cancel an order",
        tag: "Orders",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Order id (UUID)",
        }],
        request_body: Some(SchemaRef {
            name: "CancelOrderRequest",
            content_type: "application/json",
        }),
        responses: &[ResponseSpec {
            status: 200,
            description: "Cancelled",
            schema: None,
        }],
    },
    // ── Image upload (presigned URL flow) ─────────────────────────────
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/RequestImageUploadUrl",
        },
        method: "POST",
        path: "/admin/products/{id}/image-upload-url",
        operation_id: "request_image_upload_url",
        summary: "Get a presigned PUT URL for uploading a product image",
        tag: "Products",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Product id (UUID)",
        }],
        request_body: Some(SchemaRef {
            name: "ImageUploadUrlBody",
            content_type: "application/json",
        }),
        responses: &[
            ResponseSpec {
                status: 200,
                description: "Presigned URL",
                schema: Some(SchemaRef {
                    name: "RequestImageUploadUrlResponse",
                    content_type: "application/json",
                }),
            },
            ResponseSpec {
                status: 404,
                description: "Product not found",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "product",
            grpc_method: "product.v1.ProductService/ConfirmImageUpload",
        },
        method: "POST",
        path: "/admin/products/{id}/confirm-image",
        operation_id: "confirm_image_upload",
        summary: "Confirm a product image was successfully uploaded to blob storage",
        tag: "Products",
        params: &[Param {
            name: "id",
            location: "path",
            required: true,
            schema_type: "string",
            description: "Product id (UUID)",
        }],
        request_body: Some(SchemaRef {
            name: "ConfirmImageBody",
            content_type: "application/json",
        }),
        responses: &[
            ResponseSpec {
                status: 204,
                description: "Confirmed",
                schema: None,
            },
            ResponseSpec {
                status: 404,
                description: "Product not found",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
            ResponseSpec {
                status: 409,
                description: "Product is inactive",
                schema: Some(SchemaRef {
                    name: "ProblemDetail",
                    content_type: "application/problem+json",
                }),
            },
        ],
    },
    // ── Shared reference data (REST → gRPC pass-through) ───────────────
    // Currencies
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetAllCurrencies",
        },
        method: "GET",
        path: "/admin/shared/currencies",
        operation_id: "list_currencies",
        summary: "List all currencies",
        tag: "Shared",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec {
            status: 200,
            description: "Currency list",
            schema: Some(SchemaRef { name: "CurrencyListResponse", content_type: "application/json" }),
        }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetCurrencyByCode",
        },
        method: "GET",
        path: "/admin/shared/currencies/{code}",
        operation_id: "get_currency",
        summary: "Get currency by code",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "ISO 4217 currency code (e.g. MYR)" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 200, description: "Found", schema: Some(SchemaRef { name: "CurrencyResponse", content_type: "application/json" }) },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/CreateCurrency",
        },
        method: "POST",
        path: "/admin/shared/currencies",
        operation_id: "create_currency",
        summary: "Create a currency",
        tag: "Shared",
        params: &[],
        request_body: Some(SchemaRef { name: "CreateCurrencyRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 201, description: "Created", schema: None },
            ResponseSpec { status: 400, description: "Validation error", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
            ResponseSpec { status: 409, description: "Already exists", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/UpdateCurrency",
        },
        method: "PUT",
        path: "/admin/shared/currencies/{code}",
        operation_id: "update_currency",
        summary: "Update a currency",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Currency code" }],
        request_body: Some(SchemaRef { name: "UpdateCurrencyRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 204, description: "Updated", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeleteCurrency",
        },
        method: "DELETE",
        path: "/admin/shared/currencies/{code}",
        operation_id: "delete_currency",
        summary: "Delete a currency",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Currency code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 204, description: "Deleted", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/ActivateCurrency",
        },
        method: "PUT",
        path: "/admin/shared/currencies/{code}/activate",
        operation_id: "activate_currency",
        summary: "Activate a currency",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Currency code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Activated", schema: None }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeactivateCurrency",
        },
        method: "PUT",
        path: "/admin/shared/currencies/{code}/deactivate",
        operation_id: "deactivate_currency",
        summary: "Deactivate a currency",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Currency code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Deactivated", schema: None }],
    },
    // Countries
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetAllCountries",
        },
        method: "GET",
        path: "/admin/shared/countries",
        operation_id: "list_countries",
        summary: "List all countries",
        tag: "Shared",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "Country list", schema: Some(SchemaRef { name: "CountryListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetCountryByCode",
        },
        method: "GET",
        path: "/admin/shared/countries/{code}",
        operation_id: "get_country",
        summary: "Get country by code",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "ISO 3166-1 alpha-2 country code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 200, description: "Found", schema: Some(SchemaRef { name: "CountryResponse", content_type: "application/json" }) },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetCountriesByCurrency",
        },
        method: "GET",
        path: "/admin/shared/currencies/{code}/countries",
        operation_id: "list_countries_by_currency",
        summary: "List countries that use a currency",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Currency code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "Country list", schema: Some(SchemaRef { name: "CountryListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/CreateCountry",
        },
        method: "POST",
        path: "/admin/shared/countries",
        operation_id: "create_country",
        summary: "Create a country",
        tag: "Shared",
        params: &[],
        request_body: Some(SchemaRef { name: "CreateCountryRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 201, description: "Created", schema: None },
            ResponseSpec { status: 400, description: "Validation error", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
            ResponseSpec { status: 409, description: "Already exists", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/UpdateCountry",
        },
        method: "PUT",
        path: "/admin/shared/countries/{code}",
        operation_id: "update_country",
        summary: "Update a country",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Country code" }],
        request_body: Some(SchemaRef { name: "UpdateCountryRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 204, description: "Updated", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeleteCountry",
        },
        method: "DELETE",
        path: "/admin/shared/countries/{code}",
        operation_id: "delete_country",
        summary: "Delete a country",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Country code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 204, description: "Deleted", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/ActivateCountry",
        },
        method: "PUT",
        path: "/admin/shared/countries/{code}/activate",
        operation_id: "activate_country",
        summary: "Activate a country",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Country code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Activated", schema: None }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeactivateCountry",
        },
        method: "PUT",
        path: "/admin/shared/countries/{code}/deactivate",
        operation_id: "deactivate_country",
        summary: "Deactivate a country",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Country code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Deactivated", schema: None }],
    },
    // States
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetAllStates",
        },
        method: "GET",
        path: "/admin/shared/states",
        operation_id: "list_states",
        summary: "List all states",
        tag: "Shared",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "State list", schema: Some(SchemaRef { name: "StateListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetStateByCode",
        },
        method: "GET",
        path: "/admin/shared/states/{code}",
        operation_id: "get_state",
        summary: "Get state by code",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 200, description: "Found", schema: Some(SchemaRef { name: "StateResponse", content_type: "application/json" }) },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetStatesByCountry",
        },
        method: "GET",
        path: "/admin/shared/countries/{code}/states",
        operation_id: "list_states_by_country",
        summary: "List states for a country",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Country code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "State list", schema: Some(SchemaRef { name: "StateListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/CreateState",
        },
        method: "POST",
        path: "/admin/shared/states",
        operation_id: "create_state",
        summary: "Create a state",
        tag: "Shared",
        params: &[],
        request_body: Some(SchemaRef { name: "CreateStateRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 201, description: "Created", schema: None },
            ResponseSpec { status: 400, description: "Validation error", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
            ResponseSpec { status: 409, description: "Already exists", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/UpdateState",
        },
        method: "PUT",
        path: "/admin/shared/states/{code}",
        operation_id: "update_state",
        summary: "Update a state",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: Some(SchemaRef { name: "UpdateStateRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 204, description: "Updated", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeleteState",
        },
        method: "DELETE",
        path: "/admin/shared/states/{code}",
        operation_id: "delete_state",
        summary: "Delete a state",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 204, description: "Deleted", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/ActivateState",
        },
        method: "PUT",
        path: "/admin/shared/states/{code}/activate",
        operation_id: "activate_state",
        summary: "Activate a state",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Activated", schema: None }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeactivateState",
        },
        method: "PUT",
        path: "/admin/shared/states/{code}/deactivate",
        operation_id: "deactivate_state",
        summary: "Deactivate a state",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Deactivated", schema: None }],
    },
    // Cities
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetAllCities",
        },
        method: "GET",
        path: "/admin/shared/cities",
        operation_id: "list_cities",
        summary: "List all cities",
        tag: "Shared",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "City list", schema: Some(SchemaRef { name: "CityListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetCityByCode",
        },
        method: "GET",
        path: "/admin/shared/cities/{code}",
        operation_id: "get_city",
        summary: "Get city by code",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 200, description: "Found", schema: Some(SchemaRef { name: "CityResponse", content_type: "application/json" }) },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetCitiesByState",
        },
        method: "GET",
        path: "/admin/shared/states/{code}/cities",
        operation_id: "list_cities_by_state",
        summary: "List cities for a state",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "State code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "City list", schema: Some(SchemaRef { name: "CityListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/CreateCity",
        },
        method: "POST",
        path: "/admin/shared/cities",
        operation_id: "create_city",
        summary: "Create a city",
        tag: "Shared",
        params: &[],
        request_body: Some(SchemaRef { name: "CreateCityRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 201, description: "Created", schema: None },
            ResponseSpec { status: 400, description: "Validation error", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
            ResponseSpec { status: 409, description: "Already exists", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/UpdateCity",
        },
        method: "PUT",
        path: "/admin/shared/cities/{code}",
        operation_id: "update_city",
        summary: "Update a city",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: Some(SchemaRef { name: "UpdateCityRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 204, description: "Updated", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeleteCity",
        },
        method: "DELETE",
        path: "/admin/shared/cities/{code}",
        operation_id: "delete_city",
        summary: "Delete a city",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 204, description: "Deleted", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/ActivateCity",
        },
        method: "PUT",
        path: "/admin/shared/cities/{code}/activate",
        operation_id: "activate_city",
        summary: "Activate a city",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Activated", schema: None }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeactivateCity",
        },
        method: "PUT",
        path: "/admin/shared/cities/{code}/deactivate",
        operation_id: "deactivate_city",
        summary: "Deactivate a city",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Deactivated", schema: None }],
    },
    // Pincodes
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetAllPincodes",
        },
        method: "GET",
        path: "/admin/shared/pincodes",
        operation_id: "list_pincodes",
        summary: "List all pincodes",
        tag: "Shared",
        params: &[],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "Pincode list", schema: Some(SchemaRef { name: "PincodeListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetPincodeByCode",
        },
        method: "GET",
        path: "/admin/shared/pincodes/{code}",
        operation_id: "get_pincode",
        summary: "Get pincode by code",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Pincode" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 200, description: "Found", schema: Some(SchemaRef { name: "PincodeResponse", content_type: "application/json" }) },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/GetPincodesByCity",
        },
        method: "GET",
        path: "/admin/shared/cities/{code}/pincodes",
        operation_id: "list_pincodes_by_city",
        summary: "List pincodes for a city",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "City code" }],
        request_body: None,
        responses: &[ResponseSpec { status: 200, description: "Pincode list", schema: Some(SchemaRef { name: "PincodeListResponse", content_type: "application/json" }) }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/CreatePincode",
        },
        method: "POST",
        path: "/admin/shared/pincodes",
        operation_id: "create_pincode",
        summary: "Create a pincode",
        tag: "Shared",
        params: &[],
        request_body: Some(SchemaRef { name: "CreatePincodeRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 201, description: "Created", schema: None },
            ResponseSpec { status: 400, description: "Validation error", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
            ResponseSpec { status: 409, description: "Already exists", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/UpdatePincode",
        },
        method: "PUT",
        path: "/admin/shared/pincodes/{code}",
        operation_id: "update_pincode",
        summary: "Update a pincode",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Pincode" }],
        request_body: Some(SchemaRef { name: "UpdatePincodeRequest", content_type: "application/json" }),
        responses: &[
            ResponseSpec { status: 204, description: "Updated", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeletePincode",
        },
        method: "DELETE",
        path: "/admin/shared/pincodes/{code}",
        operation_id: "delete_pincode",
        summary: "Delete a pincode",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Pincode" }],
        request_body: None,
        responses: &[
            ResponseSpec { status: 204, description: "Deleted", schema: None },
            ResponseSpec { status: 404, description: "Not found", schema: Some(SchemaRef { name: "ProblemDetail", content_type: "application/problem+json" }) },
        ],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/ActivatePincode",
        },
        method: "PUT",
        path: "/admin/shared/pincodes/{code}/activate",
        operation_id: "activate_pincode",
        summary: "Activate a pincode",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Pincode" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Activated", schema: None }],
    },
    ApiRoute {
        kind: RouteKind::Passthrough {
            upstream: "shared",
            grpc_method: "shared.v1.SharedService/DeactivatePincode",
        },
        method: "PUT",
        path: "/admin/shared/pincodes/{code}/deactivate",
        operation_id: "deactivate_pincode",
        summary: "Deactivate a pincode",
        tag: "Shared",
        params: &[Param { name: "code", location: "path", required: true, schema_type: "string", description: "Pincode" }],
        request_body: None,
        responses: &[ResponseSpec { status: 204, description: "Deactivated", schema: None }],
    },
];
